# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Apps.widget.commom import MyListView


class Ui_phase_one_widget(object):
    def setupUi(self, phase_one_widget):
        phase_one_widget.setObjectName("phase_one_widget")
        phase_one_widget.resize(900, 600)
        phase_one_widget.setMaximumSize(QtCore.QSize(900, 600))
        self.open_file = QtWidgets.QPushButton(phase_one_widget)
        self.open_file.setGeometry(QtCore.QRect(50, 10, 91, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file.setIcon(icon)
        self.open_file.setObjectName("open_file")
        self.graphic = QtWidgets.QGraphicsView(phase_one_widget)
        self.graphic.setGeometry(QtCore.QRect(450, 10, 401, 331))
        self.graphic.setObjectName("graphic")
        self.p1_predict = QtWidgets.QPushButton(phase_one_widget)
        self.p1_predict.setGeometry(QtCore.QRect(240, 10, 151, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-input-power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p1_predict.setIcon(icon1)
        self.p1_predict.setObjectName("p1_predict")
        self.text_logs = QtWidgets.QTextBrowser(phase_one_widget)
        self.text_logs.setGeometry(QtCore.QRect(450, 430, 411, 141))
        self.text_logs.setObjectName("text_logs")
        self.label = QtWidgets.QLabel(phase_one_widget)
        self.label.setGeometry(QtCore.QRect(450, 410, 51, 16))
        self.label.setObjectName("label")
        self.fn_chooser = QtWidgets.QLineEdit(phase_one_widget)
        self.fn_chooser.setGeometry(QtCore.QRect(50, 60, 331, 21))
        self.fn_chooser.setObjectName("fn_chooser")
        self.open_dir = QtWidgets.QPushButton(phase_one_widget)
        self.open_dir.setGeometry(QtCore.QRect(150, 10, 81, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-find-in-page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_dir.setIcon(icon2)
        self.open_dir.setObjectName("open_dir")
        self.listView = MyListView(phase_one_widget)
        self.listView.setGeometry(QtCore.QRect(50, 130, 331, 441))
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(phase_one_widget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 121, 16))
        self.label_2.setObjectName("label_2")
        self.show_net_btn = QtWidgets.QPushButton(phase_one_widget)
        self.show_net_btn.setGeometry(QtCore.QRect(450, 350, 121, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-restore.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.show_net_btn.setIcon(icon3)
        self.show_net_btn.setObjectName("show_net_btn")
        self.show_files_btn = QtWidgets.QPushButton(phase_one_widget)
        self.show_files_btn.setGeometry(QtCore.QRect(580, 350, 111, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-share-boxed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_files_btn.setIcon(icon4)
        self.show_files_btn.setFlat(False)
        self.show_files_btn.setObjectName("show_files_btn")
        self.previous_btn = QtWidgets.QPushButton(phase_one_widget)
        self.previous_btn.setGeometry(QtCore.QRect(710, 350, 31, 32))
        self.previous_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_btn.setIcon(icon5)
        self.previous_btn.setObjectName("previous_btn")
        self.next_btn = QtWidgets.QPushButton(phase_one_widget)
        self.next_btn.setGeometry(QtCore.QRect(750, 350, 31, 32))
        self.next_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon6)
        self.next_btn.setObjectName("next_btn")
        self.exp_btn = QtWidgets.QPushButton(phase_one_widget)
        self.exp_btn.setGeometry(QtCore.QRect(790, 350, 61, 32))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-exposure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exp_btn.setIcon(icon7)
        self.exp_btn.setObjectName("exp_btn")
        self.progressBar = QtWidgets.QProgressBar(phase_one_widget)
        self.progressBar.setGeometry(QtCore.QRect(460, 385, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setVisible(False)

        self.retranslateUi(phase_one_widget)
        QtCore.QMetaObject.connectSlotsByName(phase_one_widget)

    def retranslateUi(self, phase_one_widget):
        _translate = QtCore.QCoreApplication.translate
        phase_one_widget.setWindowTitle(_translate("phase_one_widget", "Form"))
        self.open_file.setText(_translate("phase_one_widget", "打开"))
        self.p1_predict.setText(_translate("phase_one_widget", "一阶段解析"))
        self.label.setText(_translate("phase_one_widget", "Log"))
        self.open_dir.setText(_translate("phase_one_widget", "读取"))
        self.label_2.setText(_translate("phase_one_widget", "Dir Content View"))
        self.show_net_btn.setText(_translate("phase_one_widget", "显示网络结果"))
        self.show_files_btn.setText(_translate("phase_one_widget", "显示原图"))
        self.exp_btn.setText(_translate("phase_one_widget", "导出"))
