# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phase_two(object):
    def setupUi(self, phase_two):
        phase_two.setObjectName("phase_two")
        phase_two.resize(900, 613)
        phase_two.setMaximumSize(QtCore.QSize(900, 680))
        self.label = QtWidgets.QLabel(phase_two)
        self.label.setGeometry(QtCore.QRect(450, 410, 51, 16))
        self.label.setObjectName("label")
        self.previous_btn = QtWidgets.QPushButton(phase_two)
        self.previous_btn.setGeometry(QtCore.QRect(750, 160, 41, 32))
        self.previous_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_btn.setIcon(icon)
        self.previous_btn.setObjectName("previous_btn")
        self.text_logs = QtWidgets.QTextBrowser(phase_two)
        self.text_logs.setGeometry(QtCore.QRect(450, 430, 411, 141))
        self.text_logs.setObjectName("text_logs")
        self.next_btn = QtWidgets.QPushButton(phase_two)
        self.next_btn.setGeometry(QtCore.QRect(810, 160, 41, 32))
        self.next_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon1)
        self.next_btn.setObjectName("next_btn")
        self.graphic = QtWidgets.QGraphicsView(phase_two)
        self.graphic.setGeometry(QtCore.QRect(450, 10, 401, 131))
        self.graphic.setObjectName("graphic")
        self.fn_chooser = QtWidgets.QLineEdit(phase_two)
        self.fn_chooser.setGeometry(QtCore.QRect(50, 60, 331, 21))
        self.fn_chooser.setObjectName("fn_chooser")
        self.show_net_btn = QtWidgets.QPushButton(phase_two)
        self.show_net_btn.setGeometry(QtCore.QRect(450, 160, 131, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-restore.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.show_net_btn.setIcon(icon2)
        self.show_net_btn.setObjectName("show_net_btn")
        self.open_file = QtWidgets.QPushButton(phase_two)
        self.open_file.setGeometry(QtCore.QRect(50, 10, 91, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file.setIcon(icon3)
        self.open_file.setObjectName("open_file")
        self.p1_predict = QtWidgets.QPushButton(phase_two)
        self.p1_predict.setGeometry(QtCore.QRect(240, 10, 151, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-input-power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p1_predict.setIcon(icon4)
        self.p1_predict.setObjectName("p1_predict")
        self.label_2 = QtWidgets.QLabel(phase_two)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 61, 16))
        self.label_2.setObjectName("label_2")
        self.open_dir = QtWidgets.QPushButton(phase_two)
        self.open_dir.setGeometry(QtCore.QRect(150, 10, 81, 32))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-find-in-page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_dir.setIcon(icon5)
        self.open_dir.setObjectName("open_dir")
        self.treeView = QtWidgets.QTreeView(phase_two)
        self.treeView.setGeometry(QtCore.QRect(50, 130, 331, 441))
        self.treeView.setObjectName("treeView")
        self.folder_name = QtWidgets.QLabel(phase_two)
        self.folder_name.setGeometry(QtCore.QRect(120, 110, 251, 16))
        self.folder_name.setObjectName("folder_name")
        self.graphic_origin = QtWidgets.QGraphicsView(phase_two)
        self.graphic_origin.setGeometry(QtCore.QRect(450, 230, 401, 111))
        self.graphic_origin.setObjectName("graphic_origin")
        self.label_3 = QtWidgets.QLabel(phase_two)
        self.label_3.setGeometry(QtCore.QRect(450, 210, 51, 16))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(phase_two)
        self.progressBar.setGeometry(QtCore.QRect(450, 370, 391, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(phase_two)
        QtCore.QMetaObject.connectSlotsByName(phase_two)

    def retranslateUi(self, phase_two):
        _translate = QtCore.QCoreApplication.translate
        phase_two.setWindowTitle(_translate("phase_two", "Form"))
        self.label.setText(_translate("phase_two", "Log"))
        self.show_net_btn.setText(_translate("phase_two", "显示网络结果"))
        self.open_file.setText(_translate("phase_two", "打开"))
        self.p1_predict.setText(_translate("phase_two", "二阶段解析"))
        self.label_2.setText(_translate("phase_two", "File View: "))
        self.open_dir.setText(_translate("phase_two", "读取"))
        self.folder_name.setText(_translate("phase_two", "None"))
        self.label_3.setText(_translate("phase_two", "Origin"))
